/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type { Book } from './models/Book';
export type { Chapter } from './models/Chapter';
export type { CreateAnswersheetManagementDto } from './models/CreateAnswersheetManagementDto';
export type { CreateAttachDto } from './models/CreateAttachDto';
export type { CreateBookDto } from './models/CreateBookDto';
export type { CreateBookIntroDto } from './models/CreateBookIntroDto';
export type { CreateBookReferenceDto } from './models/CreateBookReferenceDto';
export type { CreateChapterDto } from './models/CreateChapterDto';
export type { CreateEssayQuestionsDto } from './models/CreateEssayQuestionsDto';
export type { CreateFieldOfStudyDto } from './models/CreateFieldOfStudyDto';
export type { CreateGradeLevelDto } from './models/CreateGradeLevelDto';
export type { CreateKaranbalaDto } from './models/CreateKaranbalaDto';
export type { CreateLearningMaterialDto } from './models/CreateLearningMaterialDto';
export { CreateObjectiveTestDto } from './models/CreateObjectiveTestDto';
export type { CreateObjectiveTestManagementDto } from './models/CreateObjectiveTestManagementDto';
export type { CreateOnlineGradeReportDto } from './models/CreateOnlineGradeReportDto';
export { CreateQuestionDto } from './models/CreateQuestionDto';
export type { CreateSampleExampleQuestionsDto } from './models/CreateSampleExampleQuestionsDto';
export type { CreateSampleTestQuestionsDto } from './models/CreateSampleTestQuestionsDto';
export type { CreateSectionDto } from './models/CreateSectionDto';
export { CreateStandardDto } from './models/CreateStandardDto';
export type { CreateSubjectDto } from './models/CreateSubjectDto';
export type { CreateTermOfStudyDto } from './models/CreateTermOfStudyDto';
export type { CreateTipAndTestDto } from './models/CreateTipAndTestDto';
export type { CreateUserDto } from './models/CreateUserDto';
export type { GradeLevel } from './models/GradeLevel';
export type { ObjectiveTest } from './models/ObjectiveTest';
export type { Section } from './models/Section';
export type { SigninUserDto } from './models/SigninUserDto';
export type { Subject } from './models/Subject';
export type { UpdateAnswersheetManagementDto } from './models/UpdateAnswersheetManagementDto';
export type { UpdateAttachDto } from './models/UpdateAttachDto';
export type { UpdateBookDto } from './models/UpdateBookDto';
export type { UpdateBookIntroDto } from './models/UpdateBookIntroDto';
export type { UpdateBookReferenceDto } from './models/UpdateBookReferenceDto';
export type { UpdateChapterDto } from './models/UpdateChapterDto';
export type { UpdateEssayQuestionDto } from './models/UpdateEssayQuestionDto';
export type { UpdateFieldOfStudyDto } from './models/UpdateFieldOfStudyDto';
export type { UpdateGradeLevelDto } from './models/UpdateGradeLevelDto';
export type { UpdateKaranbalaDto } from './models/UpdateKaranbalaDto';
export type { UpdateLearningMaterialDto } from './models/UpdateLearningMaterialDto';
export { UpdateObjectiveTestDto } from './models/UpdateObjectiveTestDto';
export type { UpdateObjectiveTestManagementDto } from './models/UpdateObjectiveTestManagementDto';
export type { UpdateOnlineGradeReportDto } from './models/UpdateOnlineGradeReportDto';
export { UpdateQuestionDto } from './models/UpdateQuestionDto';
export type { UpdateSampleExampleQuestionsDto } from './models/UpdateSampleExampleQuestionsDto';
export type { UpdateSampleTestQuestionsDto } from './models/UpdateSampleTestQuestionsDto';
export type { UpdateSectionDto } from './models/UpdateSectionDto';
export { UpdateStandardDto } from './models/UpdateStandardDto';
export type { UpdateSubjectDto } from './models/UpdateSubjectDto';
export type { UpdateTermOfStudyDto } from './models/UpdateTermOfStudyDto';
export type { UpdateTipAndTestDto } from './models/UpdateTipAndTestDto';

export { AnswersheetManagementService } from './services/AnswersheetManagementService';
export { AttachService } from './services/AttachService';
export { AuthService } from './services/AuthService';
export { BookService } from './services/BookService';
export { BookIntroService } from './services/BookIntroService';
export { BookReferenceService } from './services/BookReferenceService';
export { ChapterService } from './services/ChapterService';
export { EssayQuestionService } from './services/EssayQuestionService';
export { FieldOfStudyService } from './services/FieldOfStudyService';
export { GradeLevelService } from './services/GradeLevelService';
export { HomeService } from './services/HomeService';
export { KaranbalaService } from './services/KaranbalaService';
export { LearningMaterialService } from './services/LearningMaterialService';
export { ObjectiveTestService } from './services/ObjectiveTestService';
export { ObjectiveTestManagementService } from './services/ObjectiveTestManagementService';
export { OnlineGradeReportService } from './services/OnlineGradeReportService';
export { QuestionService } from './services/QuestionService';
export { SampleExampleQuestionsService } from './services/SampleExampleQuestionsService';
export { SampleTestQuestionsService } from './services/SampleTestQuestionsService';
export { SectionService } from './services/SectionService';
export { StandardService } from './services/StandardService';
export { SubjectService } from './services/SubjectService';
export { TermOfStudyService } from './services/TermOfStudyService';
export { TipAndTestService } from './services/TipAndTestService';
export { UserService } from './services/UserService';
